const WORD_PAIRS = [
    {a:"Laptop", b:"Tablet"}, {a:"Sun", b:"Star"}, {a:"Lemon", b:"Lime"}, {a:"Chair", b:"Stool"}, {a:"Airplane", b:"Helicopter"},
    {a:"Ocean", b:"Lake"}, {a:"Pencil", b:"Pen"}, {a:"Backpack", b:"Handbag"}, {a:"Socks", b:"Stockings"}, {a:"Mirror", b:"Window"},
    {a:"Blanket", b:"Quilt"}, {a:"Candle", b:"Flashlight"}, {a:"Wallet", b:"Purse"}, {a:"Curtain", b:"Blind"}, {a:"Soap", b:"Shampoo"},
    {a:"Toothbrush", b:"Floss"}, {a:"Hammer", b:"Mallet"}, {a:"Ladder", b:"Stairs"}, {a:"Clock", b:"Watch"}, {a:"Bucket", b:"Basket"},
    {a:"Umbrella", b:"Raincoat"}, {a:"Coffee", b:"Tea"}, {a:"Butter", b:"Margarine"}, {a:"Bread", b:"Toast"}, {a:"Milk", b:"Cream"},
    {a:"Cookie", b:"Biscuit"}, {a:"Honey", b:"Syrup"}, {a:"Salt", b:"Pepper"}, {a:"Orange", b:"Tangerine"}, {a:"Apple", b:"Pear"},
    {a:"Pizza", b:"Flatbread"}, {a:"Burger", b:"Sandwich"}, {a:"Ice Cream", b:"Frozen Yogurt"}, {a:"Coca-Cola", b:"Pepsi"},
    {a:"Wine", b:"Grape Juice"}, {a:"Onion", b:"Garlic"}, {a:"Steak", b:"Chop"}, {a:"Cake", b:"Muffin"}, {a:"Tomato", b:"Ketchup"},
    {a:"Sugar", b:"Sweetener"}, {a:"Noodle", b:"Pasta"}, {a:"Tiger", b:"Lion"}, {a:"Wolf", b:"Husky"}, {a:"Rabbit", b:"Hare"},
    {a:"Frog", b:"Toad"}, {a:"Bee", b:"Wasp"}, {a:"Butterfly", b:"Moth"}, {a:"Crocodile", b:"Alligator"}, {a:"Dolphin", b:"Whale"},
    {a:"Rat", b:"Mouse"}, {a:"Horse", b:"Donkey"}, {a:"Sheep", b:"Goat"}, {a:"Mountain", b:"Hill"}, {a:"River", b:"Stream"},
    {a:"Rain", b:"Drizzle"}, {a:"Snow", b:"Hail"}, {a:"Forest", b:"Jungle"}, {a:"Island", b:"Peninsula"}, {a:"Flower", b:"Plant"},
    {a:"Grass", b:"Moss"}, {a:"Cave", b:"Tunnel"}, {a:"Smartphone", b:"Telephone"}, {a:"Television", b:"Cinema"}, {a:"Radio", b:"Podcast"},
    {a:"Email", b:"Letter"}, {a:"Keyboard", b:"Typewriter"}, {a:"Mouse", b:"Trackpad"}, {a:"Headphones", b:"Speakers"},
    {a:"Camera", b:"Camcorder"}, {a:"Website", b:"Application"}, {a:"Password", b:"PIN code"}, {a:"Soccer", b:"Football"},
    {a:"Tennis", b:"Badminton"}, {a:"Running", b:"Jogging"}, {a:"Swimming", b:"Diving"}, {a:"Hiking", b:"Walking"},
    {a:"Bicycle", b:"Motorcycle"}, {a:"Guitar", b:"Ukulele"}, {a:"Piano", b:"Keyboard"}, {a:"Painting", b:"Drawing"},
    {a:"Dancing", b:"Ballet"}, {a:"Doctor", b:"Nurse"}, {a:"Teacher", b:"Professor"}, {a:"Police", b:"Soldier"},
    {a:"Chef", b:"Cook"}, {a:"Actor", b:"Singer"}, {a:"Library", b:"Bookstore"}, {a:"Hospital", b:"Clinic"},
    {a:"Hotel", b:"Motel"}, {a:"Bank", b:"ATM"}, {a:"Airport", b:"Train Station"}, {a:"Dream", b:"Nightmare"},
    {a:"Circle", b:"Oval"}, {a:"Square", b:"Rectangle"}, {a:"Red", b:"Pink"}, {a:"Blue", b:"Purple"}, {a:"Warm", b:"Hot"},
    {a:"Cold", b:"Freezing"}, {a:"Quick", b:"Fast"}, {a:"Happy", b:"Excited"}, {a:"Angry", b:"Annoyed"}, {a:"Friend", b:"Partner"},
    {a:"Morning", b:"Dawn"}, {a:"Night", b:"Midnight"}, {a:"Holiday", b:"Weekend"}, {a:"Movie", b:"Cartoon"},
    {a:"Taco", b:"Burrito"}, {a:"Pancake", b:"Waffle"}, {a:"Sushi", b:"Sashimi"}, {a:"Jam", b:"Jelly"}, {a:"Bacon", b:"Sausage"},
    {a:"Broccoli", b:"Cauliflower"}, {a:"Peach", b:"Nectarine"}, {a:"Ketchup", b:"Mustard"}, {a:"Mayonnaise", b:"Aioli"}, {a:"Spaghetti", b:"Macaroni"},
    {a:"Soup", b:"Stew"}, {a:"Smoothie", b:"Milkshake"}, {a:"Juice", b:"Soda"}, {a:"Lemonade", b:"Iced Tea"}, {a:"Pie", b:"Tart"},
    {a:"Croissant", b:"Bagel"}, {a:"Chips", b:"Fries"}, {a:"Pretzel", b:"Cracker"}, {a:"Popsicle", b:"Ice Cream Cone"}, {a:"Omelet", b:"Scrambled Eggs"},
    {a:"Pork", b:"Beef"}, {a:"Chicken", b:"Turkey"}, {a:"Shrimp", b:"Prawn"}, {a:"Crab", b:"Lobster"}, {a:"Carrot", b:"Parsnip"},
    {a:"Cabbage", b:"Lettuce"}, {a:"Spinach", b:"Kale"}, {a:"Garlic", b:"Ginger"}, {a:"Walnut", b:"Pecan"}, {a:"Peanut", b:"Almond"},
    {a:"Mushroom", b:"Truffle"}, {a:"Vanilla", b:"Chocolate"}, {a:"Caramel", b:"Butterscotch"}, {a:"Oatmeal", b:"Cereal"}, {a:"Cheetah", b:"Leopard"},
    {a:"Turtle", b:"Tortoise"}, {a:"Crow", b:"Raven"}, {a:"Llama", b:"Alpaca"}, {a:"Camel", b:"Dromedary"}, {a:"Falcon", b:"Hawk"},
    {a:"Eagle", b:"Vulture"}, {a:"Pigeon", b:"Dove"}, {a:"Seagull", b:"Pelican"}, {a:"Penguin", b:"Puffin"}, {a:"Ostrich", b:"Emu"},
    {a:"Kangaroo", b:"Wallaby"}, {a:"Koala", b:"Sloth"}, {a:"Panda", b:"Grizzly Bear"}, {a:"Polar Bear", b:"Brown Bear"}, {a:"Monkey", b:"Ape"},
    {a:"Chimpanzee", b:"Gorilla"}, {a:"Fox", b:"Coyote"}, {a:"Jackal", b:"Hyena"}, {a:"Deer", b:"Elk"}, {a:"Moose", b:"Reindeer"},
    {a:"Zebra", b:"Horse"}, {a:"Rhino", b:"Hippo"}, {a:"Elephant", b:"Mammoth"}, {a:"Pig", b:"Boar"}, {a:"Snake", b:"Lizard"},
    {a:"Iguana", b:"Chameleon"}, {a:"Salamander", b:"Gecko"}, {a:"Shark", b:"Dolphin"}, {a:"Octopus", b:"Squid"}, {a:"Jellyfish", b:"Starfish"},
    {a:"Snail", b:"Slug"}, {a:"Worm", b:"Caterpillar"}, {a:"Centipede", b:"Millipede"}, {a:"Spider", b:"Scorpion"}, {a:"Ant", b:"Termite"},
    {a:"Beetle", b:"Roach"}, {a:"Fly", b:"Mosquito"}, {a:"Flea", b:"Tick"}, {a:"Sofa", b:"Couch"}, {a:"Rug", b:"Carpet"},
    {a:"Mug", b:"Cup"}, {a:"Fork", b:"Spoon"}, {a:"Plate", b:"Bowl"}, {a:"Pot", b:"Pan"}, {a:"Oven", b:"Stove"},
    {a:"Microwave", b:"Toaster"}, {a:"Fridge", b:"Freezer"}, {a:"Dishwasher", b:"Sink"}, {a:"Broom", b:"Mop"}, {a:"Vacuum", b:"Dustpan"},
    {a:"Towel", b:"Washcloth"}, {a:"Bed", b:"Cot"}, {a:"Pillow", b:"Cushion"}, {a:"Wardrobe", b:"Closet"}, {a:"Dresser", b:"Cabinet"},
    {a:"Desk", b:"Table"}, {a:"Bookshelf", b:"Rack"}, {a:"Lamp", b:"Lantern"}, {a:"Vase", b:"Pot"}, {a:"Frame", b:"Canvas"},
    {a:"Door", b:"Gate"}, {a:"Roof", b:"Ceiling"}, {a:"Floor", b:"Ground"}, {a:"Wall", b:"Fence"}, {a:"Balcony", b:"Patio"},
    {a:"Garage", b:"Shed"}, {a:"Attic", b:"Basement"}, {a:"Jacket", b:"Coat"}, {a:"Sweater", b:"Hoodie"}, {a:"Sneakers", b:"Boots"},
    {a:"Scarf", b:"Shawl"}, {a:"Hat", b:"Cap"}, {a:"Gloves", b:"Mittens"}, {a:"Jeans", b:"Trousers"}, {a:"Shorts", b:"Trunks"},
    {a:"Skirt", b:"Dress"}, {a:"Suit", b:"Tuxedo"}, {a:"Shirt", b:"Blouse"}, {a:"T-shirt", b:"Polo"}, {a:"Belt", b:"Suspenders"},
    {a:"Tie", b:"Bowtie"}, {a:"Necklace", b:"Bracelet"}, {a:"Ring", b:"Earrings"}, {a:"Glasses", b:"Goggles"}, {a:"Sunglasses", b:"Visor"},
    {a:"Slippers", b:"Sandals"}, {a:"Heels", b:"Flats"}, {a:"Uniform", b:"Costume"}, {a:"Pajamas", b:"Nightgown"}, {a:"Underwear", b:"Lingerie"},
    {a:"Swimsuit", b:"Bikini"}, {a:"Monitor", b:"Screen"}, {a:"Smartwatch", b:"Fitness Tracker"}, {a:"Router", b:"Modem"}, {a:"Charger", b:"Cable"},
    {a:"Battery", b:"Power Bank"}, {a:"Flash Drive", b:"Hard Drive"}, {a:"Printer", b:"Scanner"}, {a:"Microphone", b:"Megaphone"}, {a:"Projector", b:"Display"},
    {a:"Console", b:"PC"}, {a:"Controller", b:"Joystick"}, {a:"Server", b:"Database"}, {a:"App", b:"Software"}, {a:"Algorithm", b:"Code"},
    {a:"Wrench", b:"Pliers"}, {a:"Screwdriver", b:"Drill"}, {a:"Nail", b:"Screw"}, {a:"Axe", b:"Hatchet"}, {a:"Saw", b:"Chainsaw"},
    {a:"Shovel", b:"Spade"}, {a:"Rake", b:"Hoe"}, {a:"Scissors", b:"Shears"}, {a:"Tape", b:"Glue"}, {a:"Ruler", b:"Tape Measure"},
    {a:"Pond", b:"Lake"}, {a:"Creek", b:"River"}, {a:"Desert", b:"Savanna"}, {a:"Canyon", b:"Valley"}, {a:"Cliff", b:"Ridge"},
    {a:"Bay", b:"Gulf"}, {a:"Glacier", b:"Iceberg"}, {a:"Volcano", b:"Crater"}, {a:"Earthquake", b:"Tsunami"}, {a:"Tornado", b:"Hurricane"},
    {a:"Storm", b:"Blizzard"}, {a:"Breeze", b:"Wind"}, {a:"Pebble", b:"Rock"}, {a:"Boulder", b:"Stone"}, {a:"Sand", b:"Dust"},
    {a:"Dirt", b:"Soil"}, {a:"Clay", b:"Mud"}, {a:"Leaf", b:"Petal"}, {a:"Branch", b:"Twig"}, {a:"Trunk", b:"Bark"},
    {a:"Root", b:"Stem"}, {a:"Bush", b:"Shrub"}, {a:"Vine", b:"Ivy"}, {a:"Weed", b:"Fern"}, {a:"Car", b:"Truck"},
    {a:"Van", b:"Bus"}, {a:"Taxi", b:"Uber"}, {a:"Subway", b:"Train"}, {a:"Tram", b:"Trolley"}, {a:"Helicopter", b:"Drone"},
    {a:"Jet", b:"Glider"}, {a:"Rocket", b:"Missile"}, {a:"Ship", b:"Boat"}, {a:"Yacht", b:"Sailboat"}, {a:"Canoe", b:"Kayak"},
    {a:"Raft", b:"Ferry"}, {a:"Submarine", b:"Torpedo"}, {a:"Skateboard", b:"Rollerblades"}, {a:"Scooter", b:"Hoverboard"}, {a:"Tractor", b:"Bulldozer"},
    {a:"Ambulance", b:"Fire Truck"}, {a:"Engine", b:"Motor"}, {a:"Tire", b:"Wheel"}, {a:"Brake", b:"Pedal"}, {a:"Arm", b:"Leg"},
    {a:"Hand", b:"Foot"}, {a:"Eye", b:"Ear"}, {a:"Nose", b:"Mouth"}, {a:"Lip", b:"Tongue"}, {a:"Tooth", b:"Gum"},
    {a:"Hair", b:"Beard"}, {a:"Mustache", b:"Goatee"}, {a:"Cheek", b:"Chin"}, {a:"Forehead", b:"Temple"}, {a:"Neck", b:"Throat"},
    {a:"Shoulder", b:"Back"}, {a:"Chest", b:"Stomach"}, {a:"Heart", b:"Lung"}, {a:"Brain", b:"Mind"}, {a:"Bone", b:"Muscle"},
    {a:"Skin", b:"Flesh"}, {a:"Blood", b:"Vein"}, {a:"Finger", b:"Toe"}, {a:"Thumb", b:"Pinky"}, {a:"Baby", b:"Toddler"},
    {a:"Teenager", b:"Adult"}, {a:"Brother", b:"Sister"}, {a:"Uncle", b:"Aunt"}, {a:"Nephew", b:"Niece"}, {a:"Cousin", b:"Sibling"},
    {a:"Grandfather", b:"Grandmother"}, {a:"King", b:"Emperor"}, {a:"Queen", b:"Princess"}, {a:"Prince", b:"Duke"}, {a:"Author", b:"Writer"},
    {a:"Poet", b:"Novelist"}, {a:"Journalist", b:"Reporter"}, {a:"Editor", b:"Publisher"}, {a:"Artist", b:"Painter"}, {a:"Sculptor", b:"Potter"},
    {a:"Musician", b:"Composer"}, {a:"Director", b:"Producer"}, {a:"Photographer", b:"Cameraman"}, {a:"Lawyer", b:"Judge"}, {a:"Detective", b:"Inspector"},
    {a:"Mayor", b:"Governor"}, {a:"President", b:"Prime Minister"}, {a:"Senator", b:"Congressman"}, {a:"Dentist", b:"Surgeon"}, {a:"Pharmacist", b:"Chemist"},
    {a:"Engineer", b:"Architect"}, {a:"Mechanic", b:"Plumber"}, {a:"Electrician", b:"Carpenter"}, {a:"Farmer", b:"Rancher"}, {a:"Pilot", b:"Captain"},
    {a:"Sailor", b:"Marine"}, {a:"Cashier", b:"Clerk"}, {a:"Waiter", b:"Bartender"}, {a:"Barista", b:"Baker"}, {a:"Baseball", b:"Softball"},
    {a:"Basketball", b:"Volleyball"}, {a:"Golf", b:"Mini Golf"}, {a:"Bowling", b:"Billiards"}, {a:"Boxing", b:"Wrestling"}, {a:"Karate", b:"Judo"},
    {a:"Fencing", b:"Archery"}, {a:"Skiing", b:"Snowboarding"}, {a:"Surfing", b:"Skateboarding"}, {a:"Gymnastics", b:"Acrobatics"}, {a:"Chess", b:"Checkers"},
    {a:"Poker", b:"Blackjack"}, {a:"Dominoes", b:"Mahjong"}, {a:"Puzzle", b:"Riddle"}, {a:"Dice", b:"Cards"}, {a:"Magic", b:"Illusion"},
    {a:"Origami", b:"Crafts"}, {a:"Knitting", b:"Sewing"}, {a:"Flute", b:"Clarinet"}, {a:"Trumpet", b:"Saxophone"}, {a:"Violin", b:"Cello"},
    {a:"Drum", b:"Cymbal"}, {a:"Symphony", b:"Orchestra"}, {a:"Choir", b:"Band"}, {a:"Concert", b:"Festival"}, {a:"Past", b:"Future"},
    {a:"History", b:"Legend"}, {a:"Myth", b:"Fable"}, {a:"Truth", b:"Fact"}, {a:"Lie", b:"Secret"}, {a:"Joke", b:"Prank"},
    {a:"Laugh", b:"Smile"}, {a:"Cry", b:"Weep"}, {a:"Fear", b:"Terror"}, {a:"Brave", b:"Bold"}, {a:"Smart", b:"Wise"},
    {a:"Fool", b:"Idiot"}, {a:"Rich", b:"Wealthy"}, {a:"Poor", b:"Broke"}, {a:"Cheap", b:"Free"}, {a:"Expensive", b:"Costly"},
    {a:"Buy", b:"Sell"}, {a:"Rent", b:"Lease"}, {a:"Borrow", b:"Lend"}, {a:"Save", b:"Spend"}, {a:"Win", b:"Succeed"},
    {a:"Lose", b:"Fail"}, {a:"Start", b:"Begin"}, {a:"End", b:"Finish"}, {a:"Stop", b:"Pause"}, {a:"Second", b:"Minute"},
    {a:"Hour", b:"Day"}, {a:"Week", b:"Month"}, {a:"Year", b:"Decade"}, {a:"Century", b:"Millennium"}, {a:"Spring", b:"Summer"},
    {a:"Autumn", b:"Winter"}, {a:"North", b:"South"}, {a:"East", b:"West"}, {a:"Left", b:"Right"}, {a:"Up", b:"Down"},
    {a:"Over", b:"Under"}, {a:"Inside", b:"Outside"}, {a:"Near", b:"Far"}, {a:"High", b:"Low"}, {a:"Heavy", b:"Light"},
    {a:"Hard", b:"Soft"}, {a:"Rough", b:"Smooth"}, {a:"Sharp", b:"Dull"}, {a:"Bright", b:"Dim"}, {a:"Loud", b:"Quiet"},
    {a:"Sweet", b:"Sour"}, {a:"Spicy", b:"Bitter"}, {a:"Clean", b:"Tidy"}, {a:"Gold", b:"Silver"}, {a:"Bronze", b:"Copper"},
    {a:"Iron", b:"Steel"}, {a:"Diamond", b:"Ruby"}, {a:"Emerald", b:"Sapphire"}, {a:"Pearl", b:"Opal"}, {a:"Necklace", b:"Choker"},
    {a:"Suitcase", b:"Briefcase"}, {a:"Mop", b:"Swiffer"}, {a:"Stool", b:"Bench"}, {a:"Couch", b:"Loveseat"}, {a:"Recliner", b:"Armchair"},
    {a:"Marker", b:"Highlighter"}, {a:"Notebook", b:"Notepad"}, {a:"Folder", b:"Binder"}, {a:"Stapler", b:"Paperclip"}, {a:"Eraser", b:"Whiteout"},
    {a:"Chalk", b:"Charcoal"}, {a:"Easel", b:"Canvas"}, {a:"Sword", b:"Dagger"}, {a:"Shield", b:"Armor"}, {a:"Bow", b:"Crossbow"},
    {a:"Spear", b:"Javelin"}, {a:"Castle", b:"Palace"}, {a:"Fortress", b:"Tower"}, {a:"Village", b:"Town"}, {a:"City", b:"Metropolis"},
    {a:"Street", b:"Avenue"}, {a:"Road", b:"Highway"}, {a:"Alley", b:"Lane"}, {a:"Path", b:"Trail"}, {a:"Bridge", b:"Tunnel"},
    {a:"Harbor", b:"Port"}, {a:"Dock", b:"Pier"}, {a:"Station", b:"Terminal"}, {a:"Ticket", b:"Pass"}, {a:"Map", b:"Globe"},
    {a:"Compass", b:"GPS"}, {a:"Lantern", b:"Torch"}, {a:"Match", b:"Lighter"}, {a:"Fire", b:"Flame"}, {a:"Smoke", b:"Ash"}
];
